import { useTheme } from './ThemeProvider'
import { APP_NAME } from '../lib/brand'
import { cn } from '../lib/utils'

type LogoProps = {
  /** Square edge length in px. Defaults to 32. */
  size?: number
  /**
   * Ignored since the 2026-08 rebrand, kept so existing call sites compile.
   *
   * The mark is now a RASTER: the gradient A-I monogram from the brand kit's
   * main_logo.png (background removed, served from /logo/mark.png). A raster cannot be
   * recoloured with currentColor the way the old vector mark was, so `fill` has nothing
   * to act on. The gradient indigo-violet reads on both light and dark surfaces, which
   * is the trade the rebrand made explicitly: one authentic logo everywhere instead of
   * a theme-adaptive redrawing of it.
   */
  fill?: string
  className?: string
}

/**
 * The A-Identity mark (2026-08 rebrand): the gradient A-I monogram, crossed by a
 * ribbon. Source of truth is the brand kit's main_logo.png; /logo/mark.png is the
 * background-removed square crop of its mark, and /logo/logo-full.png is the full
 * lockup with the wordmark. All derived assets (favicon.png, apple-touch-icon.png,
 * docs/logo.png, the OG card) are cut from the same source, never redrawn.
 */
export default function Logo({ size = 32, className }: LogoProps) {
  return (
    <img
      src="/logo/mark.png"
      width={size}
      height={size}
      className={className}
      alt=""
      aria-hidden="true"
      draggable={false}
    />
  )
}

/** Canvas aspect of /brand/lockup-horizontal-full-*.png. Both cuts share it. */
const LOCKUP_ASPECT = 1812 / 480

/**
 * The horizontal lockup: the gradient mark with the brand wordmark next to it.
 *
 * The mark is theme-neutral by design (see above), but the WORDMARK is not: it is flat
 * ink on light and flat cream on dark, and the brand kit ships both cuts. Printing the
 * ink cut on a dark surface is the one thing the rebrand's "one authentic logo" rule
 * cannot absorb, because the wordmark simply disappears. So this picks the cut that
 * matches the theme and leaves the mark alone.
 *
 * Both files are generated by scripts/gen-brand-logos.mjs from the same source as
 * /logo/mark.png, so this is the real lockup rather than the mark with type set beside
 * it. Exactly ONE of the two is ever requested: a hidden <img> is still downloaded, so
 * a CSS-only `dark:hidden` swap would cost both files for no benefit.
 *
 * Sizing is by HEIGHT, in canvas px. The artwork sits inside a 1812x480 field with even
 * padding, so the mark renders at about 0.78 of the height given here: 40 reproduces the
 * 32px mark the navbar carried before this component existed.
 */
export function Lockup({
  height = 40,
  className,
  /** Above-the-fold lockups (the navbar) should not be lazy. */
  eager = false,
  /** Empty when an ancestor already carries the accessible name, e.g. a labelled link. */
  alt = APP_NAME,
}: {
  height?: number
  className?: string
  eager?: boolean
  alt?: string
}) {
  const { theme } = useTheme()
  const src =
    theme === 'dark'
      ? '/brand/lockup-horizontal-full-cream.png'
      : '/brand/lockup-horizontal-full-ink.png'
  return (
    <img
      src={src}
      width={Math.round(height * LOCKUP_ASPECT)}
      height={height}
      style={{ height }}
      className={cn('w-auto select-none', className)}
      alt={alt}
      loading={eager ? 'eager' : 'lazy'}
      decoding="async"
      draggable={false}
    />
  )
}
